name: Build and Deploy

on: [ push, pull_request ]

jobs:
   lint-client:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v2
            with:
               fetch-depth: 0
         -
            name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: 12
         -
            shell: bash
            run: |
               pushd client
               npm ci
               npm run lint
   lint-server:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v2
            with:
               fetch-depth: 0
         -
            name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: 12
         -
            shell: bash
            run: |
               pushd server
               npm ci
               npm run lint
   build:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v2
            with:
               fetch-depth: 0
         -
            name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: 12
         -
            shell: bash
            run: |
               pushd client
               npm ci
               npm run build
         -
            uses: actions/upload-artifact@v2
            with:
               name:  client-dist
               path: client/dist
   deploy:
      if: github.ref == 'refs/heads/master'
      needs: [ lint-client, lint-server, build ]
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/download-artifact@v2
            with:
               name: client-dist
               path: dist
         -
            uses: peaceiris/actions-gh-pages@v3
            with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: dist
